"""
Futuristic-themed methodology deck: risk-factor calibration (fit quality),
Monte Carlo simulation design, regression/simulation date construction,
Brownian-bridge interpolation, forward-matching proof, and pricing
accuracy (analytic vs. Monte Carlo) -- built from the REAL charts/numbers
generated by build_calibration_charts.py (run that script first).

    python risk_engine/examples/build_methodology_ppt.py
"""
import os

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
from pptx.oxml.ns import qn

HERE = os.path.dirname(__file__)
OUT_PATH = os.path.join(HERE, "Capitolis_Risk_Engine_Methodology.pptx")

# ---------------------------------------------------------------- theme
BG = RGBColor(0x05, 0x07, 0x12)          # near-black navy
PANEL = RGBColor(0x0B, 0x10, 0x24)       # slightly lighter panel
CYAN = RGBColor(0x00, 0xE5, 0xFF)
MAGENTA = RGBColor(0xFF, 0x2E, 0xC4)
AMBER = RGBColor(0xFF, 0xB8, 0x2E)
GREEN = RGBColor(0x39, 0xFF, 0x9D)
WHITE = RGBColor(0xF2, 0xF5, 0xFF)
GREY = RGBColor(0x8A, 0x93, 0xB8)
GRID_LINE = RGBColor(0x1C, 0x24, 0x44)

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)

FONT = "Segoe UI"
FONT_MONO = "Consolas"


def _set_bg(slide, color=BG):
    bg = slide.background
    bg.fill.solid()
    bg.fill.fore_color.rgb = color


def _no_line(shape):
    shape.line.fill.background()


def _glow_rect(slide, left, top, width, height, color=CYAN, fill=None):
    """A thin accent rectangle (bar/underline), no border."""
    shp = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
    shp.fill.solid()
    shp.fill.fore_color.rgb = fill or color
    _no_line(shp)
    shp.shadow.inherit = False
    return shp


def _textbox(slide, left, top, width, height, text, size=14, color=WHITE, bold=False,
             font=FONT, align=PP_ALIGN.LEFT, italic=False, anchor=MSO_ANCHOR.TOP, line_spacing=1.0):
    tb = slide.shapes.add_textbox(left, top, width, height)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    lines = text.split("\n")
    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = line
        p.alignment = align
        p.line_spacing = line_spacing
        for run in p.runs:
            run.font.size = Pt(size)
            run.font.color.rgb = color
            run.font.bold = bold
            run.font.italic = italic
            run.font.name = font
    return tb


def _bullets(slide, left, top, width, height, items, size=13, color=WHITE, font=FONT,
             marker_color=CYAN, line_spacing=1.15, space_after=6):
    tb = slide.shapes.add_textbox(left, top, width, height)
    tf = tb.text_frame
    tf.word_wrap = True
    for i, (text, sub) in enumerate(items):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.line_spacing = line_spacing
        p.space_after = Pt(space_after)
        run_marker = p.add_run()
        run_marker.text = "> "
        run_marker.font.size = Pt(size)
        run_marker.font.color.rgb = marker_color
        run_marker.font.name = FONT_MONO
        run_marker.font.bold = True
        run_text = p.add_run()
        run_text.text = text
        run_text.font.size = Pt(size)
        run_text.font.color.rgb = color
        run_text.font.name = font
        if sub:
            p2 = tf.add_paragraph()
            p2.line_spacing = line_spacing
            p2.space_after = Pt(space_after)
            r = p2.add_run()
            r.text = "    " + sub
            r.font.size = Pt(size - 2)
            r.font.color.rgb = GREY
            r.font.name = font
            r.font.italic = True
    return tb


def _header(slide, kicker, title, num, total):
    _glow_rect(slide, Inches(0), Inches(0), SLIDE_W, Inches(0.08), color=CYAN)
    _textbox(slide, Inches(0.55), Inches(0.28), Inches(8), Inches(0.35), kicker.upper(),
             size=12, color=CYAN, font=FONT_MONO, bold=True)
    _textbox(slide, Inches(0.55), Inches(0.6), Inches(11.5), Inches(0.8), title,
             size=28, color=WHITE, bold=True)
    _glow_rect(slide, Inches(0.55), Inches(1.35), Inches(1.4), Pt(3), color=MAGENTA)
    _textbox(slide, Inches(12.0), Inches(0.3), Inches(0.9), Inches(0.35), f"{num:02d} / {total:02d}",
             size=11, color=GREY, font=FONT_MONO, align=PP_ALIGN.RIGHT)


def _picture_framed(slide, path, left, top, width=None, height=None, caption=None):
    if not os.path.exists(path):
        _textbox(slide, left, top, width or Inches(6), Inches(0.4), f"[missing: {os.path.basename(path)}]",
                 size=11, color=MAGENTA, italic=True)
        return
    pic = slide.shapes.add_picture(path, left, top, width=width, height=height)
    # thin cyan frame
    frame = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, pic.width, pic.height)
    frame.fill.background()
    frame.line.color.rgb = GRID_LINE
    frame.line.width = Pt(1)
    frame.shadow.inherit = False
    if caption:
        _textbox(slide, left, top + pic.height + Pt(4), pic.width, Inches(0.3), caption,
                 size=10, color=GREY, italic=True, align=PP_ALIGN.CENTER)
    return pic


TOTAL_SLIDES = 15
_counter = {"n": 0}


def new_slide(prs, kicker, title):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_bg(slide)
    _counter["n"] += 1
    _header(slide, kicker, title, _counter["n"], TOTAL_SLIDES)
    return slide


def build():
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H

    C = os.path.join(HERE, "chart_{}.png").format

    # ============================================================ 1. TITLE
    s = prs.slides.add_slide(prs.slide_layouts[6])
    _set_bg(s)
    _glow_rect(s, Inches(0), Inches(3.55), SLIDE_W, Pt(2), color=CYAN)
    _textbox(s, Inches(0.8), Inches(2.3), Inches(11.5), Inches(0.5), "CAPITOLIS x UC BERKELEY MFE",
             size=14, color=CYAN, font=FONT_MONO, bold=True)
    _textbox(s, Inches(0.8), Inches(2.75), Inches(11.7), Inches(1.6),
             "Counterparty Credit Risk Engine", size=40, color=WHITE, bold=True)
    _textbox(s, Inches(0.8), Inches(3.75), Inches(11.5), Inches(0.6),
             "Model Calibration | Monte Carlo Simulation | Forward-Matching | Pricing Accuracy",
             size=16, color=GREY)
    _textbox(s, Inches(0.8), Inches(6.7), Inches(6), Inches(0.4),
             "risk_engine // methodology deck", size=11, color=GREY, font=FONT_MONO)

    # ============================================================ 2. PIPELINE OVERVIEW
    s = new_slide(prs, "System Overview", "End-to-End Pipeline")
    steps = [
        ("SOURCE", "Real market data: Bloomberg (USD/JPY curves, swaption cubes, SPX/TOPIX, USDJPY), FRED, Yahoo, Databento, OPRA"),
        ("CALIBRATE", "LGM2F_SV (rates), GBM_SV (equity), FXGBM_SV (FX) -- fit to real curves/vol surfaces, forward-matching by construction"),
        ("SIMULATE", "One joint Monte Carlo draw, N correlated factors, single Cholesky decomposition, fixed simulation grid"),
        ("INTERPOLATE", "Brownian-bridge bridge to any off-grid regression date -- no re-simulation"),
        ("PRICE", "Multiprocess pricing across paths x regression dates -> NPV0 / NPV10 (MPoR curves)"),
        ("AGGREGATE", "EE / PFE / MPE / EEPE, SA-CCR delta, vega, CVA / DVA / FVA"),
    ]
    x0, y0, w, gap = Inches(0.55), Inches(1.7), Inches(1.95), Inches(0.15)
    for i, (label, desc) in enumerate(steps):
        left = x0 + i * (w + gap)
        box = slide_box = None
        card = prs.slides[-1].shapes.add_shape(MSO_SHAPE.RECTANGLE, left, y0, w, Inches(4.6))
        card.fill.solid()
        card.fill.fore_color.rgb = PANEL
        card.line.color.rgb = CYAN if i % 2 == 0 else MAGENTA
        card.line.width = Pt(1.25)
        card.shadow.inherit = False
        _textbox(prs.slides[-1], left + Inches(0.12), y0 + Inches(0.18), w - Inches(0.24), Inches(0.5),
                 f"{i+1:02d}", size=22, color=(CYAN if i % 2 == 0 else MAGENTA), font=FONT_MONO, bold=True)
        _textbox(prs.slides[-1], left + Inches(0.12), y0 + Inches(0.75), w - Inches(0.24), Inches(0.4),
                 label, size=13, color=WHITE, bold=True, font=FONT_MONO)
        _textbox(prs.slides[-1], left + Inches(0.12), y0 + Inches(1.2), w - Inches(0.24), Inches(3.2),
                 desc, size=10.5, color=GREY, line_spacing=1.2)
        if i < len(steps) - 1:
            _textbox(prs.slides[-1], left + w, y0 + Inches(2.1), gap, Inches(0.5), ">", size=16,
                     color=GREY, align=PP_ALIGN.CENTER, font=FONT_MONO)

    # ============================================================ 3. RATE MODEL CALIBRATION FIT (USD)
    s = new_slide(prs, "Calibration Fit -- Rates", "USD SOFR: Real Curve vs. LGM2F_SV Reconstruction")
    _picture_framed(s, C("usd_curve_fit"), Inches(0.55), Inches(1.6), width=Inches(7.4))
    _bullets(s, Inches(8.3), Inches(1.7), Inches(4.5), Inches(4.5), [
        ("Real Bloomberg SWPM zero curve", "32 pillars, 1W-50Y, dealer-computed discount factors"),
        ("LGM reconstructs DF(t,T) exactly", "DF(t,T) = DF(0,T)/DF(0,t) . exp(-H.x(t) - 0.5H^2.zeta(t))"),
        ("Max deviation: 5.65 bp", "across the full 0.05Y-30Y tenor range -- forward-matching by construction"),
        ("Not an approximation", "the fit is exact GIVEN the deterministic t=0 state; residual bp reflects interpolation grid density, not model error"),
    ], size=12.5)

    # ============================================================ 4. RATE MODEL CALIBRATION FIT (JPY)
    s = new_slide(prs, "Calibration Fit -- Rates", "JPY OIS: Real Curve vs. LGM2F_SV Reconstruction")
    _picture_framed(s, C("jpy_curve_fit"), Inches(0.55), Inches(1.6), width=Inches(7.4))
    _bullets(s, Inches(8.3), Inches(1.7), Inches(4.5), Inches(4.5), [
        ("First real JPY curve this project has used", "replaces a flat placeholder used throughout earlier phases"),
        ("Real Bloomberg JPY OIS SWPM curve", "35 pillars, 1W-40Y"),
        ("Max deviation: 1.53 bp", "even tighter fit than USD"),
        ("Purpose: drives FX drift only", "no JPY-currency cashflow in this book -- the factor exists purely to give USD/JPY a REAL simulated rate differential"),
    ], size=12.5)

    # ============================================================ 5. FORWARD CURVES
    s = new_slide(prs, "Term Structure", "Spot Curve vs. Forward Curve (Projected Ahead)")
    _picture_framed(s, C("usd_forward_curve"), Inches(0.45), Inches(1.6), width=Inches(6.0))
    _picture_framed(s, C("jpy_forward_curve"), Inches(6.85), Inches(1.6), width=Inches(6.0))
    _textbox(s, Inches(0.55), Inches(6.55), Inches(12), Inches(0.6),
             "1-year forward rate (t, t+1Y) implied by today's fit, alongside the spot zero curve -- the term structure the model projects forward, not just today's shape.",
             size=12, color=GREY, italic=True)

    # ============================================================ 6. SWAPTION VOL -- TERM STRUCTURE
    s = new_slide(prs, "Calibration Fit -- Vol", "Real ATM Swaption Vol: Term Structure")
    _picture_framed(s, C("usd_swaption_term"), Inches(0.45), Inches(1.6), width=Inches(6.0))
    _picture_framed(s, C("jpy_swaption_term"), Inches(6.85), Inches(1.6), width=Inches(6.0))
    _textbox(s, Inches(0.55), Inches(6.55), Inches(12), Inches(0.6),
             "Real Bloomberg VCUB ATM normal-vol cubes (21 expiries x 15 swap tenors) -- feeds LGM-SV's theta (long-run variance level) via the longest-tenor ATM vol.",
             size=12, color=GREY, italic=True)

    # ============================================================ 7. SWAPTION VOL -- SKEW/CURVATURE INPUT
    s = new_slide(prs, "Calibration Fit -- Vol", "Swap-Tenor Axis: Skew / Curvature Fit Input")
    _picture_framed(s, C("usd_swaption_slice"), Inches(0.45), Inches(1.6), width=Inches(6.0))
    _picture_framed(s, C("jpy_swaption_slice"), Inches(6.85), Inches(1.6), width=Inches(6.0))
    _bullets(s, Inches(0.55), Inches(6.35), Inches(12), Inches(0.9), [
        ("fit_skew_smile() reads this axis", "the swap-tenor dependence at the cube's longest expiry -- >=3 points required, this cube has 15"),
        ("Produces real rho (skew) and eta (curvature)", "for LGM2F_SV -- previously a literature-prior fallback with no real smile data"),
    ], size=11.5)

    # ============================================================ 8. EQUITY / FX VOL
    s = new_slide(prs, "Calibration Fit -- Equity & FX", "Realized Vol Term Structure (Model Input = Fit)")
    _picture_framed(s, C("equity_usd_vol"), Inches(0.4), Inches(1.55), width=Inches(4.15))
    _picture_framed(s, C("equity_jpy_vol"), Inches(4.65), Inches(1.55), width=Inches(4.15))
    _picture_framed(s, C("fx_vol"), Inches(8.9), Inches(1.55), width=Inches(4.15))
    _bullets(s, Inches(0.55), Inches(6.15), Inches(12.2), Inches(1.1), [
        ("Equity/FX have no 'curve' to fit", "GBM_SV/FXGBM_SV calibrate directly to the realized-vol term structure -- the sourced input IS the fitted term structure by construction (bootstrap_sigma reproduces it exactly)"),
        ("SPX/TOPIX implied/realized ratio applied", "USD names x1.0712, JPY names x0.9143 -- a real, market-observed risk-premium adjustment on top of realized vol"),
    ], size=11.5)

    # ============================================================ 9. SIMULATION GRID / REGRESSION DATES
    s = new_slide(prs, "Monte Carlo Design", "Simulation Grid & Regression Dates")
    _bullets(s, Inches(0.55), Inches(1.7), Inches(5.9), Inches(4.9), [
        ("Simulation grid (FIXED, MPoR-independent)", "weekly through month 3, monthly through year 1, quarterly beyond -- 28 dates to book horizon"),
        ("Reporting anchors", "monthly through year 1, quarterly beyond -- 18 anchors, independent cadence from the simulation grid"),
        ("Regression dates (what pricing actually needs)", "every trade's own cashflow dates + each anchor's MPoR window endpoints (t-1bd, t+10bd) -- 94 dates, mostly OFF the simulation grid"),
        ("Why two grids, not one", "simulating densely enough to hit every cashflow date directly would be far more expensive than simulating once, coarsely, and INTERPOLATING to any date needed"),
    ], size=13, line_spacing=1.25, space_after=10)
    card = prs.slides[-1].shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(6.85), Inches(1.7), Inches(5.9), Inches(4.9))
    card.fill.solid(); card.fill.fore_color.rgb = PANEL
    card.line.color.rgb = CYAN; card.line.width = Pt(1)
    card.shadow.inherit = False
    _textbox(prs.slides[-1], Inches(7.05), Inches(1.9), Inches(5.5), Inches(0.4), "GRID TIMELINE (illustrative)",
             size=12, color=CYAN, font=FONT_MONO, bold=True)
    timeline_rows = [
        ("Simulation grid", "|  .  .  .  .    .    .    .  |", CYAN),
        ("Reporting anchors", "|    .      .      .      .   |", MAGENTA),
        ("Regression dates", "| . .. . . .. . . .. . . .. . |", AMBER),
    ]
    ty = Inches(2.5)
    for label, viz, color in timeline_rows:
        _textbox(prs.slides[-1], Inches(7.05), ty, Inches(2.2), Inches(0.4), label, size=11, color=WHITE)
        _textbox(prs.slides[-1], Inches(9.1), ty, Inches(3.4), Inches(0.4), viz, size=13, color=color, font=FONT_MONO)
        ty += Inches(0.55)
    _textbox(prs.slides[-1], Inches(7.05), Inches(4.4), Inches(5.5), Inches(1.9),
             "ref_date -------------------------------------------> horizon\n\n"
             "Regression dates land wherever a trade's cashflow or an\n"
             "MPoR window boundary falls -- almost never exactly on a\n"
             "simulation-grid date.",
             size=11, color=GREY, font=FONT_MONO, line_spacing=1.3)

    # ============================================================ 10. JOINT SIMULATION / CHOLESKY
    s = new_slide(prs, "Monte Carlo Design", "Joint Correlated Simulation")
    _bullets(s, Inches(0.55), Inches(1.7), Inches(6.2), Inches(4.8), [
        ("One N-driver correlated draw", "every factor's Brownian driver(s) -- USD rate (2F), JPY rate (2F), 37 equities, FX -- share ONE Cholesky decomposition"),
        ("rho = L . L^T", "real sourced pairwise correlations (Yahoo realized returns) assembled into one correlation matrix"),
        ("Z_joint = Z_indep @ L^T", "independent standard normals correlated via the Cholesky factor -- single draw, sliced per factor"),
        ("PSD repair", "eigenvalue clipping ensures a valid (positive semi-definite) correlation matrix before factorization -- real sourced correlations are not guaranteed PSD"),
        ("Why this matters for netting", "genuine cross-trade, cross-asset-class correlation in netted exposure -- not independent per-trade noise"),
    ], size=12.5, line_spacing=1.2, space_after=9)
    # simple driver diagram
    card = prs.slides[-1].shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(7.1), Inches(1.7), Inches(5.65), Inches(4.8))
    card.fill.solid(); card.fill.fore_color.rgb = PANEL
    card.line.color.rgb = MAGENTA; card.line.width = Pt(1)
    card.shadow.inherit = False
    _textbox(prs.slides[-1], Inches(7.3), Inches(1.9), Inches(5.2), Inches(0.4), "DRIVER LAYOUT",
             size=12, color=MAGENTA, font=FONT_MONO, bold=True)
    drivers = ["RATE_USD  (2 drivers)", "RATE_JPY  (2 drivers)", "EQ_<isin> x 37  (1 each)", "FX_USDJPY  (1 driver)"]
    dy = Inches(2.5)
    for d in drivers:
        _glow_rect(prs.slides[-1], Inches(7.3), dy + Pt(6), Inches(0.18), Inches(0.18), color=CYAN)
        _textbox(prs.slides[-1], Inches(7.6), dy, Inches(4.9), Inches(0.4), d, size=13, color=WHITE, font=FONT_MONO)
        dy += Inches(0.55)
    _textbox(prs.slides[-1], Inches(7.3), dy + Inches(0.2), Inches(5.2), Inches(1.6),
             "-> 41 total Brownian drivers\n-> ONE 41x41 correlation matrix\n-> ONE Cholesky factorization per run",
             size=13, color=GREEN, font=FONT_MONO, line_spacing=1.4)

    # ============================================================ 11. BROWNIAN BRIDGE INTERPOLATION
    s = new_slide(prs, "Interpolation", "Brownian-Bridge Bridge to Off-Grid Dates")
    _bullets(s, Inches(0.55), Inches(1.7), Inches(6.0), Inches(4.8), [
        ("The problem", "94 regression dates are needed; only 28 dates are actually simulated -- most regression dates fall BETWEEN grid dates"),
        ("The bridge (conditional mean)", "E[x(d)] = x(t0) + w.(x(t1)-x(t0)), w = (zeta(d)-zeta(t0)) / (zeta(t1)-zeta(t0)) -- weighted by ACCUMULATED VARIANCE, not calendar time"),
        ("Why variance-weighted", "raw time-weighting is wrong whenever vol varies across the term structure -- zeta correctly reflects how much randomness has accumulated by that point"),
        ("Exact at grid dates", "zero interpolation error when d lands exactly on a simulated date"),
        ("Extension: full bridge (opt-in)", "adds the exact conditional-VARIANCE noise term too -- implemented, validated, reproducible via deterministic seeding, correlated across factors via the same Cholesky structure"),
    ], size=12, line_spacing=1.2, space_after=8)
    card = prs.slides[-1].shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(6.85), Inches(1.7), Inches(5.9), Inches(4.8))
    card.fill.solid(); card.fill.fore_color.rgb = PANEL
    card.line.color.rgb = CYAN; card.line.width = Pt(1)
    card.shadow.inherit = False
    _textbox(prs.slides[-1], Inches(7.05), Inches(1.95), Inches(5.5), Inches(3.2),
             "E[x(d) | x(t0), x(t1)]\n"
             "   = x(t0) + w . (x(t1) - x(t0))\n\n"
             "w = zeta(d) - zeta(t0)\n"
             "    -------------------\n"
             "    zeta(t1) - zeta(t0)\n\n"
             "t0 <= d <= t1  (bracketing grid dates)",
             size=15, color=GREEN, font=FONT_MONO, line_spacing=1.5)
    _textbox(prs.slides[-1], Inches(7.05), Inches(5.5), Inches(5.5), Inches(0.9),
             "This reconstructed state feeds LGM's own closed-form\nDF(t,T) formula -- exact given the interpolated state.",
             size=11, color=GREY, italic=True, line_spacing=1.3)

    # ============================================================ 12. FORWARD-MATCHING PROOF
    s = new_slide(prs, "Validation", "Forward-Matching: Monte Carlo Proof")
    _picture_framed(s, C("usd_forward_matching_proof"), Inches(0.45), Inches(1.6), width=Inches(6.0))
    _picture_framed(s, C("jpy_forward_matching_proof"), Inches(6.85), Inches(1.6), width=Inches(6.0))
    _bullets(s, Inches(0.55), Inches(6.35), Inches(12.2), Inches(0.95), [
        ("E[DF(0,t)] over 5,000 Monte Carlo paths vs. the real input curve's own DF(0,t)", "USD: 3.32 bp max relative diff. JPY: 1.58 bp max relative diff -- genuine numerical evidence, not just a formula claim"),
    ], size=12)

    # ============================================================ 13. PRICING ACCURACY
    s = new_slide(prs, "Validation", "Pricing Accuracy: Analytic vs. Monte Carlo")
    _picture_framed(s, C("pricing_accuracy"), Inches(0.75), Inches(1.6), width=Inches(11.8))
    _bullets(s, Inches(0.55), Inches(6.15), Inches(12.2), Inches(1.1), [
        ("At 10,000 paths: BF_0003 +0.86% (bond forward -- small, stable bias)", "EQTRS_0001 -6.0% (equity TRS -- shrinking from -12.8% at 500 paths, genuine MC convergence)"),
        ("BTRS_0001 +17.9% (bond TRS -- flat since 500 paths)", "a documented, known limitation: this trade is seasoned (started before ref date), and BondTRS's return leg has no guard against summing a historical reset period -- NOT a convergence failure"),
    ], size=11.5, line_spacing=1.2)

    # ============================================================ 14. WHAT'S REAL VS PROXY
    s = new_slide(prs, "Data Provenance", "Real Data vs. Proxy vs. Placeholder")
    rows = [
        ("USD discount curve", "REAL", "Bloomberg SWPM", GREEN),
        ("USD rate vol surface", "REAL", "Bloomberg VCUB swaption cube", GREEN),
        ("JPY discount curve", "REAL", "Bloomberg SWPM", GREEN),
        ("JPY rate vol surface", "REAL", "Bloomberg VCUB swaption cube", GREEN),
        ("Equity spot / realized vol", "REAL", "Yahoo Finance", GREEN),
        ("Equity dividend yield", "REAL (partial)", "OPRA put-call parity (Databento) -- 27/37 names", AMBER),
        ("Equity vol scaling", "REAL", "SPX/TOPIX implied/realized ratio (Bloomberg)", GREEN),
        ("USD/JPY FX spot & vol", "REAL", "Bloomberg BGN history + snapshot cube", GREEN),
        ("Cross-asset correlation", "REAL", "Yahoo realized returns", GREEN),
        ("Counterparty credit spread", "PROXY", "FRED rating-tier corporate yields, tiered by book size", AMBER),
    ]
    ty = Inches(1.65)
    _textbox(s, Inches(0.55), ty, Inches(4.5), Inches(0.4), "INPUT", size=12, color=GREY, font=FONT_MONO, bold=True)
    _textbox(s, Inches(5.2), ty, Inches(2.0), Inches(0.4), "STATUS", size=12, color=GREY, font=FONT_MONO, bold=True)
    _textbox(s, Inches(7.3), ty, Inches(5.5), Inches(0.4), "SOURCE", size=12, color=GREY, font=FONT_MONO, bold=True)
    ty += Inches(0.45)
    _glow_rect(s, Inches(0.55), ty, Inches(12.2), Pt(1.5), color=GRID_LINE)
    ty += Inches(0.12)
    for name, status, source, color in rows:
        _textbox(s, Inches(0.55), ty, Inches(4.5), Inches(0.4), name, size=12, color=WHITE)
        _textbox(s, Inches(5.2), ty, Inches(2.0), Inches(0.4), status, size=11, color=color, bold=True, font=FONT_MONO)
        _textbox(s, Inches(7.3), ty, Inches(5.5), Inches(0.4), source, size=11, color=GREY)
        ty += Inches(0.46)

    # ============================================================ 15. CLOSING
    s = prs.slides.add_slide(prs.slide_layouts[6])
    _set_bg(s)
    _glow_rect(s, Inches(0), Inches(3.55), SLIDE_W, Pt(2), color=MAGENTA)
    _textbox(s, Inches(0.8), Inches(2.8), Inches(11.7), Inches(1.0), "Validated. Real Data. Real Numbers.",
             size=32, color=WHITE, bold=True)
    _textbox(s, Inches(0.8), Inches(3.75), Inches(11.5), Inches(0.6),
             "57/57 tests passing  |  sub-6bp curve fits  |  sub-3.5bp forward-matching  |  full analytic-vs-MC accuracy checks",
             size=14, color=CYAN, font=FONT_MONO)

    prs.save(OUT_PATH)
    print(f"Saved {OUT_PATH}")


if __name__ == "__main__":
    build()
